Bindu | Publish image to image artefactory

diff --git a/.github/workflows/build_publish.yml b/.github/workflows/build_publish.yml
--- a/.github/workflows/build_publish.yml
+++ b/.github/workflows/build_publish.yml
@@ -2,32 +2,29 @@ name: Build and Publish
 on:
   push:
     branches:
-      - master
-      - 'release-*'
-    tags:
-      - '[0-9]+.[0-9]+.[0-9]+'
-  workflow_run:
-    workflows: [Pull Translations from Transifex]
-    types: [completed]
-    branches:
-      - master
-      - 'release-*'
+      - CURE-Product-Master
+    paths-ignore:
+      - "**.md"
   workflow_dispatch:
 
 jobs:
-  build-publish-docker-helm:
-    name: Build & Publish Docker Image & Helm Chart
+  Trivy:
     runs-on: ubuntu-latest
-    env:
-      HELM_CHART_PATH: package/helm/
     steps:
-      - uses: actions/checkout@v2
-      - name: Set env.ARTIFACT_VERSION
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Trivy Scan
         run: |
-          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
-          ./setArtifactVersion.sh
-          rm setArtifactVersion.sh
-      - name: Use Node.js 14.x
+          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/trivy_scan.sh && chmod +x trivy_scan.sh
+          ./trivy_scan.sh
+          rm trivy_scan.sh
+  build-publish-docker:
+    name: Build & Publish Docker Image
+    runs-on: ubuntu-latest
+    needs: Trivy
+    steps:
+      - uses: actions/checkout@v3
+      - name: Use Node.js 10.16.3
         uses: actions/setup-node@v1
         with:
           node-version: 14.x
@@ -52,21 +49,14 @@ jobs:
         run: cd ui && yarn cache clean && /bin/bash ./scripts/package.sh
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
-      - name: Push Translations to Transifex
-        run: |
-          curl -o transifex.sh https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/transifex.sh
-          chmod +x transifex.sh
-          ./transifex.sh push
-          rm transifex.sh
-        env:
-          TX_TOKEN: ${{ secrets.TX_TOKEN }}
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-      - name: Login to DockerHub
-        uses: docker/login-action@v2 
+      - name: Login to GAR
+        uses: docker/login-action@v2
         with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_TOKEN }}
+          registry: us-east1-docker.pkg.dev
+          username: _json_key
+          password: ${{ secrets.CURE_EMR_DEPLOYMENTS_SERVICE_ACCOUNT_KEY }}
       - name: Docker Build and push
         uses: docker/build-push-action@v3
         with:
@@ -74,37 +64,25 @@ jobs:
           platforms: linux/amd64,linux/arm64
           file: package/docker/Dockerfile
           push: true
-          tags: bahmni/bahmni-web:${{ env.ARTIFACT_VERSION }},bahmni/bahmni-web:latest
-      - name: Update Version and Image Tag
+          tags: |
+            us-east1-docker.pkg.dev/cure-emr-gcp/bahmni/bahmni-web:${{ github.run_number }}
+            us-east1-docker.pkg.dev/cure-emr-gcp/bahmni/bahmni-web:latest
+  trigger-workflow:
+    name: Trigger workflow to deploy to Docker env
+    needs:
+      - build-publish-docker
+      - Trivy
+    runs-on: ubuntu-latest
+    env:
+      EVENT_TYPE: openmrs-module-bahmniapps-event
+    steps:
+      - name: Create repository_dispatch
         run: |
-          yq --inplace '.image.tag = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/values.yaml
-          yq --inplace '.version = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/Chart.yaml
-      - name: Helm Lint
-        run: helm lint $HELM_CHART_PATH
-
-      - name: Helm Package
-        run: helm package $HELM_CHART_PATH
-
-      - name: Checkout Charts Repository
-        uses: actions/checkout@v2
-        with:
-          repository: Bahmni/helm-charts
-          ref: gh-pages
-          path: helm-charts
-          persist-credentials: false
-
-      - name: Copy Helm Archive
-        run: cp bahmni-web-${{ env.ARTIFACT_VERSION }}.tgz helm-charts/bahmni-web/
-
-      - name: Helm Index
-        working-directory: helm-charts/
-        run: helm repo index --merge index.yaml --url https://bahmni.github.io/helm-charts/  .
-
-      - name: Commit and Push Chart Repository
-        working-directory: helm-charts/
-        run: |
-          git config user.name ${{ secrets.BAHMNI_USERNAME}}
-          git config user.email ${{ secrets.BAHMNI_EMAIL}}
-          git add .
-          git commit -m "Release of bahmni-web-${{ env.ARTIFACT_VERSION }}"
-          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmni/helm-charts.git' gh-pages
+          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.IPD_PAT }}' https://api.github.com/repos/${{ secrets.IPD_ORG_NAME }}/${{ secrets.IPD_REPOSITORY_NAME }}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+          if [ $trigger_result == 204 ];then
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi
